There's a fill dummy function in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('all/train.csv')

In [3]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [34]:
print(df.shape)
df.sample(10)

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
181,182,70,RL,54.0,7588,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,200100
508,509,70,RM,60.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2008,WD,Normal,161000
942,943,90,RL,42.0,7711,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,Oth,Abnorml,150000
1260,1261,60,RL,NaN,24682,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,181000
367,368,80,RL,101.0,9150,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,165000
1079,1080,20,RL,65.0,8775,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2007,WD,Normal,126000
306,307,60,RL,116.0,13474,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,225000
594,595,20,RL,88.0,7990,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2008,WD,Normal,110000
1058,1059,60,RL,96.0,11308,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,335000
323,324,20,RM,49.0,5820,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,126175

In [37]:
miss=df.loc[:,df.isnull().sum()!=0]
miss.sample(10)

,LotFrontage,Alley,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature
859,NaN,NaN,BrkFace,220.0,TA,TA,Mn,BLQ,Unf,SBrkr,Gd,Attchd,1968.0,Unf,TA,TA,NaN,NaN,NaN
890,60.0,NaN,None,0.0,TA,TA,Mn,Unf,Unf,SBrkr,Po,Detchd,2003.0,Unf,TA,TA,NaN,MnPrv,Shed
58,66.0,NaN,BrkFace,1031.0,Ex,TA,Gd,Unf,Unf,SBrkr,Gd,BuiltIn,2006.0,Fin,TA,TA,NaN,NaN,NaN
1083,80.0,NaN,BrkFace,425.0,TA,TA,No,BLQ,Unf,SBrkr,Gd,Attchd,1964.0,RFn,TA,TA,NaN,MnPrv,Shed
1057,NaN,NaN,None,0.0,Gd,TA,No,GLQ,Unf,SBrkr,Gd,BuiltIn,1994.0,Fin,TA,TA,NaN,NaN,NaN
424,72.0,NaN,BrkFace,74.0,Gd,TA,No,LwQ,Unf,FuseA,Gd,Attchd,1956.0,RFn,TA,TA,NaN,NaN,NaN
864,72.0,NaN,None,0.0,Ex,TA,No,Unf,Unf,SBrkr,NaN,Attchd,2008.0,Fin,TA,TA,NaN,NaN,NaN
316,94.0,NaN,BrkFace,278.0,Gd,TA,No,GLQ,Unf,SBrkr,TA,Attchd,1983.0,RFn,TA,TA,NaN,GdPrv,NaN
1306,48.0,NaN,Stone,94.0,Gd,TA,No,Unf,Unf,SBrkr,Gd,Attchd,2005.0,RFn,TA,TA,NaN,NaN,NaN
807,144.0,NaN,None,0.0,TA,TA,Gd,GLQ,Unf,SBrkr,TA,Attchd,1923.0,RFn,TA,TA,NaN,NaN,NaN

In [62]:
# Percentage of Missing:
miss.isnull().sum()/df.shape[0]*100
# creates a series object

LotFrontage     17.739726
Alley           93.767123
MasVnrType       0.547945
MasVnrArea       0.547945
BsmtQual         2.534247
BsmtCond         2.534247
BsmtExposure     2.602740
BsmtFinType1     2.534247
BsmtFinType2     2.602740
Electrical       0.068493
FireplaceQu     47.260274
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
GarageCond       5.547945
PoolQC          99.520548
Fence           80.753425
MiscFeature     96.301370
dtype: float64

In [68]:
df.loc[df.LotFrontage.isnull()]
df.loc[df.MSSubClass in [60,70,75]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [64]:
df.Fence.value_counts()

MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

In [51]:
print(df.Alley.unique())
df.loc[df.Alley=='Pave'].shape #50 times Gravel, 41 times Paved Do we need Alley at all?

[nan 'Grvl' 'Pave']

(41, 81)

PoolArea: Pool area in square feet

PoolQC: Pool quality
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       NA	No Pool

In [52]:
df.PoolQC.unique() #maybe check a trend for Excellent pools?

array([nan, 'Ex', 'Fa', 'Gd'], dtype=object)

FireplaceQu will depend on number of Fireplaces, col right before it

Fireplaces: Number of fireplaces

FireplaceQu: Fireplace quality

       Ex	Excellent - Exceptional Masonry Fireplace
       Gd	Good - Masonry Fireplace in main level
       TA	Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
       Fa	Fair - Prefabricated Fireplace in basement
       Po	Poor - Ben Franklin Stove
       NA	No Fireplace

In [24]:
garage=df[["GarageType","GarageYrBlt","GarageFinish","GarageQual","GarageCond"]]

In [29]:
garage.GarageType.unique()

array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types'],
      dtype=object)

**Some useful functions:**

df.dropna(thresh=5)

For imputation:
df["postTestScore"].fillna(df.groupby("sex")["postTestScore"].transform("mean"), inplace=True)
df[df['age'].notnull() & df['sex'].notnull()]

In [ ]:
# Sunanda's Correlation matrix:
import seaborn as sns
cmap = cmap=sns.diverging_palette(5, 250, as_cmap=True)
corr = con_var_data.corr()

def magnify():
    return [dict(selector="th",
                props=[("font-size", "7pt")]),
           dict(selector="td",
                props=[('padding', "0em 0em")]),
           dict(selector="th:hover",
                props=[("font-size", "12pt")]),
           dict(selector="tr:hover td:hover",
                props=[('max-width', '200px'),
                       ('font-size', '12pt')])
]

corr.style.background_gradient(cmap, axis=1)\
   .set_properties(**{'max-width': '80px', 'font-size': '10pt'})\
   .set_caption("Hover to magify")\
   .set_precision(2)\
   .set_table_styles(magnify())